### ISSUE TITLE
Make the header sticky

### ISSUE THREAD

**Issue by Kenny2github** [smelt-modding/smelt-modding.github.io#24]
### Feature
The header at the top of the page that says "Smelt: Batch Package Manager" (not the tab title) should be sticky (i.e. doesn't move when scrolling).
### Todo

- [ ] Make the header sticky
- [ ] Make sure it doesn't clash with anything, especially the top header
- [ ] Make sure it looks good overall

**Comment by kerrtravers** [comment]
I'll make a start on this now 👍
